Add upcoming shortcodes to example page (/examples/)
cue-lang/cuelang.org pull request #312
Opened 2023-03-03 09:17 UTC by anne-usmedia

- Added disabled links for future shortcodes 
    - Carousel 
    - CTA 
    - Quote
- Created empty pages for the upcoming shortcodes 
    - Carousel 
    - CTA 
    - Quote 
    - Tabs
- Fixed the order/weights of the shortcodes with the upcoming shortcodes in mind

For [](https://linear.app/usmedia/issue/CUE-159)

2023-03-03 12:51 UTC, JorindeUsMedia requested changes
Could we add the todo shortcode on all empty pages so it's clear when you land on them this is coming.

2023-03-06 09:07 UTC, JorindeUsMedia approved these changes

2023-03-07 13:23 UTC, Lyoness approved these changes
Importing into Gerrit

2023-03-13 13:00 UTC, Lyoness commented
Closes [40ff51b](https://github.com/cue-lang/cuelang.org/commit/40ff51b33b5060a89c7666e37eaf44f7bae31e32) as merged.

2023-03-13 13:00 UTC, closed without merging