Hugo: Add quote shortcode
cue-lang/cuelang.org pull request #319
Opened 2023-03-08 14:21 UTC by anne-usmedia

- Styling regular markdown quote
- Added quote shortcode
- Styling quote shortcode
- Added 300 weight font
- Added leading zeros in base style
- Changed lightest grey
- Added quote shortcode example page

For https://linear.app/usmedia/issue/CUE-122

2023-03-08 14:26 UTC, JorindeUsMedia commented on hugo/content/en/examples/shortcodes/quote/index.md
> +Next to the regular (very basic) [markdown blockquotes](/examples/basic/block#blockquotes), there is an option to use the `{{</* quote */>}}` shortcode. With this shortcode you can also add an author
Maybe also link to this page from the basic/block page quote section?  
"For advanced quote shortcode see: .."

2023-03-08 14:35 UTC, JorindeUsMedia requested changes

2023-03-08 14:35 UTC, JorindeUsMedia commented on hugo/assets/scss/base/base.scss
> -    --quote-background-color: #{ $c-grey--lighter };
why are these removed here? for base stuff it's best to set all variables at the top so it's easily to change them all if you have to (for instance different styling needed when base stuff is shown on a blue background)

2023-03-09 13:11 UTC, Lyoness requested changes
Quote link needs to be added to hugo/content/en/examples/_index.html

I can see it here: https://deploy-preview-319--cue.netlify.app/examples/shortcodes/quote/

But not here: 
https://deploy-preview-319--cue.netlify.app/examples/

2023-03-10 11:49 UTC, Lyoness commented
Ah yes, thanks @anne-usmedia.

2023-03-10 11:49 UTC, Lyoness approved these changes
Importing to Gerrit

2023-03-10 12:02 UTC, Lyoness commented
https://review.gerrithub.io/c/cue-lang/cuelang.org/+/550790

2023-03-13 14:26 UTC, anne-usmedia commented
@Lyoness just rebased this branch

2023-03-13 14:52 UTC, myitcv commented
Thanks @anne-usmedia - reimporting.

2023-03-13 15:02 UTC, closed without merging