Hugo/editor: Redesign Info Blocks
cue-lang/cuelang.org pull request #320
Opened 2023-03-09 09:24 UTC by anne-usmedia

- New info blocks styling
- Added exclamation mark svg
- Adjusted info blocks example page
- Added new color red to hugo and the editor
- Removed normal font weight from h4-h6

For https://linear.app/usmedia/issue/CUE-121

2023-03-09 13:13 UTC, Lyoness approved these changes
Looks great.  Importing into Gerrit.

2023-03-09 13:33 UTC, Lyoness commented
https://review.gerrithub.io/c/cue-lang/cuelang.org/+/550731

2023-03-10 09:41 UTC, JorindeUsMedia requested changes

2023-03-10 09:41 UTC, JorindeUsMedia commented on hugo/assets/scss/components/note.scss
> -    --note-bg-color: #{ $c-blue--lighter };
for themed components it's best to set the variables at the top for the default colors so it's clear what variables are themed. So these should not be removed here. For themed components we set the color variables at the top.

2023-03-10 09:41 UTC, JorindeUsMedia commented on hugo/assets/scss/components/note.scss
> +                @include svg(exclamation, $c-white);
Is it possible to render the icons inside the html? Or can it be only done via css?

2023-03-10 09:41 UTC, JorindeUsMedia commented on hugo/assets/scss/components/note.scss
> +                @include svg(exclamation, $c-white);
best to force it to be a string 'exclamation'

2023-03-13 14:01 UTC, Lyoness commented
@anne-usmedia please rebase this PR to resolve merge conflicts

2023-03-13 14:16 UTC, anne-usmedia commented
@Lyoness done

2023-03-13 14:52 UTC, myitcv commented
Thanks @anne-usmedia - reimporting now.

2023-03-13 15:02 UTC, Lyoness commented
Closes [846eb8b](https://github.com/cue-lang/cuelang.org/commit/846eb8b7dca132cd6e1f80ffdef6c44a3a44eeb4) as merged.

2023-03-13 15:02 UTC, closed without merging