Hugo: equal column width
cue-lang/cuelang.org pull request #341
Opened 2023-04-14 13:37 UTC by eva-usmedia

- added calculation of column width depending on number of columns, up to 4 columns.

For: https://linear.app/usmedia/issue/CUE-183

2023-04-14 15:41 UTC, anne-usmedia requested changes

2023-04-14 15:41 UTC, anne-usmedia commented on hugo/assets/scss/components/columns.scss
> +                --number-of-cols: 2;
Looks awesome! But I think you also need to add `flex: 0 0 50%` in this case and 33.33% and 25% in the cases below. This way the code blocks fill the width of the page, even when there is less content

2023-04-17 12:28 UTC, anne-usmedia approved these changes

2023-04-17 13:14 UTC, JorindeUsMedia approved these changes

2023-04-18 04:53 UTC, myitcv approved these changes
LGTM based on @JorindeUsMedia's review.

Will import into GerritHub now.

2023-04-18 05:02 UTC, myitcv commented
Closed via 2a1716e01144ed433d99c68d5674f0ae491b74fa

2023-04-18 05:02 UTC, closed without merging