Hugo: add anchor headings
cue-lang/cuelang.org pull request #343
Opened 2023-04-17 11:25 UTC by anne-usmedia

- Added adjusted heading renderer
- Added anchor styling
- Bigger padding on article pages to make room for anchor link
- Adjust url according to id

For https://linear.app/usmedia/issue/CUE-187

2023-04-17 11:31 UTC, JorindeUsMedia requested changes

2023-04-17 11:31 UTC, JorindeUsMedia commented on hugo/assets/scss/components/anchor.scss
> +    left: 4px;
Using left leaves a gap between h and anchor and when you hover in the gap the anchor is not visible. Maybe solve with padding-right instead?

2023-04-17 13:20 UTC, JorindeUsMedia approved these changes

2023-04-18 05:36 UTC, myitcv approved these changes
Nice! Importing to GerritHub now.

2023-04-18 05:43 UTC, myitcv commented
Closed via d0126c7b6db1420692de75b9c6f360c9db6a69d4

2023-04-18 05:43 UTC, closed without merging