Hugo: Add searchbar to menu
cue-lang/cuelang.org pull request #352
Opened 2023-05-24 08:55 UTC by anne-usmedia

- Added searchbar to menu and drawer menu
- Added typescript for menu dropdown
- Added search title text
- Added styling for searchbar in menu and drawer menu

For https://linear.app/usmedia/issue/CUE-211

2023-05-24 09:04 UTC, JorindeUsMedia requested changes

2023-05-24 09:04 UTC, JorindeUsMedia commented on hugo/assets/scss/components/header.scss
> +                transform: translate(0%, 0);
either use 0% or 0 for both, not combine. I think the style-linter want's without a unit so just 0

2023-05-24 09:06 UTC, JorindeUsMedia requested changes

2023-05-24 09:06 UTC, JorindeUsMedia commented on hugo/assets/ts/widgets/menu.ts
> +                        this.open(trigger, target);
maybe also close other dropdowns inside the menu when one is opening? in case we have more in the future

2023-05-24 09:06 UTC, JorindeUsMedia commented on hugo/layouts/partials/site/drawer-mobile.html
> +                            <form action="/search" method="get">
Is this component now reused on searchpage and in the drawer and in the menu? Consider moving it to a partial

2023-05-24 09:06 UTC, JorindeUsMedia commented on hugo/layouts/partials/site/header.html
> +                    <form action="/search" method="get">
see comment above: consider moving this to a partial because we now have duplicate code (with just a small change in classname I think) in 3 places

2023-05-24 09:06 UTC, anne-usmedia commented on hugo/assets/scss/components/header.scss
> +            top: 60px;
Nope, used that before when position was fixed, but with absolute it was too high (90px)

2023-05-24 11:11 UTC, JorindeUsMedia commented on hugo/layouts/partials/searchbar.html
> +{{/*  <form action="/search" method="get">
there is still commented code here that could be removed

2023-05-24 11:38 UTC, JorindeUsMedia approved these changes

2023-05-24 12:15 UTC, myitcv requested changes
Looks great! 

Some thoughts from my side:

* Please can we remove the animation for now. It's a bit distracting
* Clicking on the search icon, the focus should immediately be in the search bar; right now I have to click to put the focus in the search text input
* Clicking away from the search popup that appears should dismiss it. Right now the only way of dismissing it is to again press the search icon.

2023-05-25 11:55 UTC, myitcv commented
Closed via 67d63b68429a2c3479c95636c96ec3b11b5a828d

2023-05-25 11:55 UTC, closed without merging