Hugo: add copy button to code tabs
cue-lang/cuelang.org pull request #358
Opened 2023-06-01 14:33 UTC by anne-usmedia

- Add copy button to code tabs
- Add copy functionality
- Add styling for copy button + success message

For https://linear.app/usmedia/issue/CUE-166

2023-06-01 14:44 UTC, JorindeUsMedia requested changes
Styling comments:
Icon is a bit dark now and draws more attention than the code itself: use a lighter grey.
Success message font is a bit big compared to code and tabs: use smaller font?

2023-06-01 14:44 UTC, JorindeUsMedia commented on hugo/assets/scss/components/tabs.scss
> +            border-color: transparent transparent #fdc52f transparent;
Move hex value to a scss variable

2023-06-01 14:44 UTC, JorindeUsMedia commented on hugo/assets/ts/widgets/copy.ts
> +                const content: string = this.element.querySelector<HTMLElement>('.tabs__item.is-active').textContent;
you now get the content en element on every click. Maybe move them outside the click event (so 2 lines up, within the foreach, before the click)

2023-06-01 14:44 UTC, JorindeUsMedia commented on hugo/assets/ts/widgets/copy.ts
> +                const messageElement: HTMLElement = button.parentElement.querySelector('.tabs__message');
same here, see comment above

2023-06-01 14:44 UTC, JorindeUsMedia commented on hugo/layouts/shortcodes/code-tabs.html
> +<div class="code-tabs" data-copy>
you want to copy the content of the current tab so I think data-copy should be on a nested element, probably the code block itself?

2023-06-05 07:37 UTC, JorindeUsMedia approved these changes

2023-06-07 04:45 UTC, myitcv requested changes
Thanks. A couple of things I think we need to change here:

1. When we previously discussed this, we talked about the copy button not always being visible, but instead only appearing when the mouse is over the thing that can be copied. For example, see https://github.com/cue-lang/cue/blob/master/doc/contribute.md#asserting-a-developer-certificate-of-origin in an incognito window (for some reason the new-style layout always shows the copy button, which I think must be a bug)
2. Perhaps it's just me (let me know what you think) but it feels like the copy button should be within the tab, not in the tab header.
3. Please can we emulate the GitHub behaviour when the button is pressed? Changing the icon to a tick (with green border and colour), making the "Copied!" text appear to the left (makes most sense given the mouse might obstruct the text below), and using a more subtle dark grey instead of yellow. 
4. In most situations the contents of the tab will be exactly what should be copied, but not all. We need to handle situations where there are commands in a code block, and only copy the commands and not the `$ ` prefix. Only the preprocessor can know how to do this, so we need to somehow pass this text to be copied to the block in some way.

Regarding point 4, the way I have done this in the past is to render one thing, but pass a base64-encoded version of the text to be copied to a component via an attribute. That way, when the button is pressed, the attribute value is base64 decoded, and used as a the copy text, instead of what is rendered. I'm open to ideas, but something like that could work here. 

Happy to jump onto a call later to discuss.

2023-06-21 07:49 UTC, JorindeUsMedia commented
> Thanks. A couple of things I think we need to change here:
> 
> 1. When we previously discussed this, we talked about the copy button not always being visible, but instead only appearing when the mouse is over the thing that can be copied. For example, see https://github.com/cue-lang/cue/blob/master/doc/contribute.md#asserting-a-developer-certificate-of-origin in an incognito window (for some reason the new-style layout always shows the copy button, which I think must be a bug)
> 2. Perhaps it's just me (let me know what you think) but it feels like the copy button should be within the tab, not in the tab header.
> 3. Please can we emulate the GitHub behaviour when the button is pressed? Changing the icon to a tick (with green border and colour), making the "Copied!" text appear to the left (makes most sense given the mouse might obstruct the text below), and using a more subtle dark grey instead of yellow.
> 4. In most situations the contents of the tab will be exactly what should be copied, but not all. We need to handle situations where there are commands in a code block, and only copy the commands and not the `$ ` prefix. Only the preprocessor can know how to do this, so we need to somehow pass this text to be copied to the block in some way.
> 
> Regarding point 4, the way I have done this in the past is to render one thing, but pass a base64-encoded version of the text to be copied to a component via an attribute. That way, when the button is pressed, the attribute value is base64 decoded, and used as a the copy text, instead of what is rendered. I'm open to ideas, but something like that could work here.
> 
> Happy to jump onto a call later to discuss.

All of the feedback above has been implemented

2023-06-23 22:16 UTC, myitcv commented
Closed via 76cfc08539fa38f11b8040759d29ed7de9fab154

2023-06-23 22:16 UTC, closed without merging

2023-06-23 22:17 UTC, myitcv approved these changes
LGTM. Applied rebase after import.

2023-06-23 22:17 UTC, myitcv commented
Forgot to hit "submit" on the review before merging in GerritHub!