Hugo: add link to sitemap in robots.txt
cue-lang/cuelang.org pull request #394
Opened 2023-08-16 12:53 UTC by anne-usmedia

- Created robots.txt to override the autogenerated robots.txt (by Hugo)
- Added the sitemap link to the robots.txt
- https://gohugo.io/templates/robots/
- To test: /robots.txt

For https://linear.app/usmedia/issue/CUE-293

2023-08-16 13:04 UTC, JorindeUsMedia requested changes

2023-08-16 13:04 UTC, JorindeUsMedia commented on hugo/layouts/robots.txt
> +User-agent: *
According to google it would be best to also add 
Allow: / 
on the 2nd line

2023-08-16 13:04 UTC, JorindeUsMedia commented on hugo/layouts/robots.txt
> +Sitemap: https://alpha.cuelang.org/sitemap.xml
Can we make this coming from the hugo config instead of hardcoded using https://gohugo.io/functions/absurl/ ?

2023-08-23 08:08 UTC, JorindeUsMedia approved these changes

2023-08-23 08:59 UTC, jpluscplusm approved these changes

2023-08-23 09:02 UTC, jpluscplusm commented
Imported as https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1167807

2023-08-23 16:17 UTC, jpluscplusm commented
Closed via 773492ee1fe2da4a3dcfb22384a6d1d38b9c05b2.

2023-08-23 16:17 UTC, closed without merging