hugo: LHS nav improvements
cue-lang/cuelang.org pull request #395
Opened 2023-08-16 14:04 UTC by JorindeUsMedia

- Collapse tree items of non-active chapters, only show children if current page is the active chapter or a descendant of the active chapter
- Add styling to the active chapter top-level item. Switch some margins to paddings to make this possible.
- Move the styling for the border on hover to the main link/text in tree.scss because the same style is now used for every link in the tree
- Remove automatic hiding of tags pages for left hand nav
- Add `toc_hide: true` to docs pages with tags that were already not showing because of the previous tagged-pages-behaviour.

- Note: You can add the `toc_hide: true` in the front-matter to any page you don't want so show in the lhs nav. The tag overview pages can be removed if you don't need them anymore but I leave that up to CUE.

For https://linear.app/usmedia/issue/CUE-282

Test on docs pages. For instance https://deploy-preview-395--cue.netlify.app/docs/language-guide/templating/

2023-08-17 09:04 UTC, anne-usmedia requested changes

2023-08-18 05:32 UTC, myitcv commented on hugo/layouts/partials/paging/tree.html
This was one of the open questions in Linear:

> Question: is this a good UX experience (to not have something in the LHS nav that corresponds to the current page)?

I'd suggest we go with this for now; we can always re-visit later.

2023-08-18 05:32 UTC, myitcv commented on hugo/layouts/partials/paging/tree.html
>              {{ partial "paging/table-of-contents.html" (dict "toc" $toc) }}
The PR looks good to me, but I will leave this comment open for follow-up/tidy-up in a later PR.

cc @anne-usmedia @JorindeUsMedia

2023-08-18 05:33 UTC, myitcv approved these changes
LGTM from a largely visual perspective. 

Better to get this in and get feedback/thoughts on the layout.

2023-08-18 05:33 UTC, myitcv commented
Importing now.

2023-08-18 07:46 UTC, JorindeUsMedia commented on hugo/layouts/partials/paging/tree.html
Yes because now some pages are not showing in the nav anymore because of toc_hide = true than also the table of contents won't show because the item itself is not in the nav.. This problem about the table of contents will be fixed when we are going to pick up that design. Maybe after that we can check if everything in the nav & toc works as expected

2023-08-18 15:56 UTC, jpluscplusm commented
Closed via 91da7127d51c5d77025c024b4fa1216541d2e764.

2023-08-18 15:56 UTC, closed without merging