Hugo: add highlight shortcode
cue-lang/cuelang.org pull request #403
Opened 2023-08-25 13:03 UTC by anne-usmedia

- Added highlight example page (/examples/shortcodes/highlight/)
- Added link on example overview (/examples/)
- Added Related content example to blog example page (/blog/example/)
- Set up highlight shortcode
- Added highlight styling

For https://linear.app/usmedia/issue/CUE-308

2023-08-25 13:13 UTC, JorindeUsMedia requested changes
Looks good :) Just some comments.
And I'm not sure how but can we somehow improve the anchors positioning within the highlight?
![Screenshot from 2023-08-25 15-09-39](https://github.com/cue-lang/cuelang.org/assets/122357989/d97e3d98-435b-45de-8f0b-a126c8478a9b)

2023-08-25 13:13 UTC, JorindeUsMedia commented on content/blog/example/en.md
> +    - type: readingTime
is this indenting change correct?

2023-08-25 13:13 UTC, JorindeUsMedia commented on hugo/assets/scss/components/highlight.scss
> +        :first-child {
maybe use the marginless-child mixin here?

2023-08-25 13:22 UTC, anne-usmedia commented on content/blog/example/en.md
> +    - type: readingTime
yes

2023-08-25 14:35 UTC, JorindeUsMedia approved these changes

2023-08-30 04:47 UTC, myitcv commented
Looks like there is some naming inconsistency here: are we going for `spotlight` or `highlight`? The commit message, example, and actual code all seem to disagree :)

Please can we also rebase this PR?

2023-08-30 06:39 UTC, JorindeUsMedia commented
> Looks like there is some naming inconsistency here: are we going for `spotlight` or `highlight`? The commit message, example, and actual code all seem to disagree :)
> 
> Please can we also rebase this PR?

We went for 'spotlight' since 'highlight' was already reserved by hugo's code highlighting https://gohugo.io/content-management/syntax-highlighting/#highlight-shortcode

2023-08-30 08:42 UTC, myitcv approved these changes
LGTM - will import into GerritHub now, and report a different issue I've seen via Linear

2023-08-30 12:10 UTC, jpluscplusm commented
Closed via 3efff44abf7b59e152453db607fa9fa159c914cc

2023-08-30 12:10 UTC, closed without merging