Hugo: fix html validation errors for itemprop
cue-lang/cuelang.org pull request #415
Opened 2023-08-31 16:08 UTC by anne-usmedia

- Copied hugo internal schema so it can be adjusted to our needs
- Moved schema into base so the itemprops have a (correct) parent
- Added initial setup article schema

To test:
- Enter url into https://validator.w3.org/
- Enter url into https://validator.schema.org/ You should not encounter any errors or warnings about itemprops or related schema issues in the w3 validator.
You should not encounter any errors or warnings in the schema.org validator

For https://linear.app/usmedia/issue/CUE-315

2023-09-01 07:15 UTC, JorindeUsMedia requested changes

2023-09-01 07:15 UTC, JorindeUsMedia commented on hugo/layouts/partials/share.html
> +                <div><span class="share__link-text">{{ T "share_share_on" }} X (Twitter)</span></div>
div inside a is not allowed I think

2023-09-01 14:55 UTC, jpluscplusm approved these changes
LGTM modulo unresolved comment. Importing as soon as that's resolved, or another commit pushed.

2023-09-01 15:10 UTC, anne-usmedia commented on hugo/layouts/partials/share.html
> +                <div><span class="share__link-text">{{ T "share_share_on" }} X (Twitter)</span></div>
@jpluscplusm Yes!

2023-09-01 15:12 UTC, jpluscplusm commented
Imported as https://review.gerrithub.io/c/cue-lang/cuelang.org/+/1168306

2023-09-02 07:36 UTC, myitcv commented
Closed via c4c9e80f7c55c94d6730ce9ae77ebd23ef3467e4

2023-09-02 07:36 UTC, closed without merging