Hugo/playground: updates packages
cue-lang/cuelang.org pull request #441
Opened 2023-11-15 15:29 UTC by anne-usmedia

- updated hugo packages
- updated playground packages
- updated node to v20 in hugo and playground
- updated readme's with correct version numbers

For https://linear.app/usmedia/issue/CUE-198

2023-11-15 16:17 UTC, JorindeUsMedia requested changes
Something changed with eslint-plugin jsdoc which causes some linter errors:

> Definition for rule 'jsdoc/newline-after-description' was not found

I've seen these too with other projects so I'm not sure what the problem and fix is. But I notice they're now also showing up in the linter here

2023-11-17 09:23 UTC, JorindeUsMedia approved these changes

2023-11-17 11:45 UTC, ErikHendrikson approved these changes

2023-11-17 11:53 UTC, myitcv approved these changes
LGTM - importing.

2023-11-17 15:22 UTC, jpluscplusm commented
Closed via 0185c95c66d9d6833b2c145b2947f3c2e8cd8335

2023-11-17 15:22 UTC, closed without merging