Hugo: finetune spacing Spotlight shortcode
cue-lang/cuelang.org pull request #444
Opened 2023-11-16 13:12 UTC by anne-usmedia

- Added modifier attribute to spotlight shortcode
- Added the new modifier attribute to the example pages
- Rearranged the example page overview
- Improved spacing around spotlight blocks
- Moved 'last-child' styling to the related-content modifier

Testing:
- check out the example page (/examples/shortcodes/spotlight/)
- or the blog example (http://localhost:1313/blog/example/)
- or this docs page (/docs/howto/encode-json-yaml-with-cue/)

For https://linear.app/usmedia/issue/CUE-328

2023-11-17 09:35 UTC, JorindeUsMedia approved these changes

2023-11-17 11:43 UTC, ErikHendrikson approved these changes

2023-11-17 15:33 UTC, jpluscplusm requested changes
If you remove the `http://localhost:1313` element from the examples in the commit message (i.e. harmonise the 3 examples to be just URL paths), I'll get this imported 👍

2023-11-17 15:49 UTC, jpluscplusm approved these changes

2023-11-17 15:50 UTC, jpluscplusm commented
Importing now

2023-11-17 16:31 UTC, jpluscplusm commented
@anne-usmedia I'd already imported this PR before your force-push. What was in the push - content I need to include?

2023-11-17 16:32 UTC, anne-usmedia commented
@jpluscplusm sorry, I accidentally push to the wrong branch. I undid it already, sorry if this has any impact on the imported code. There should be no changes..

2023-11-17 16:34 UTC, jpluscplusm commented
>  sorry if this has any impact on the imported code.

Nope! Once I've imported a PR, there's no automatic code-level link back from Gerrit - I would have had to re-start the CL, so no damage done at all :-)

2023-11-21 13:39 UTC, jpluscplusm commented
Closed via 57199b3293de463b659d5836ef91520e2fee6b77

2023-11-21 13:39 UTC, closed without merging