playground: selected text isn't highlighted
cue-lang/cuelang.org pull request #463
Opened 2024-06-21 13:38 UTC by JorindeUsMedia

- Overwrite part of the vscode theme so the line highlight is transparent so the word highlight is also visible
 - Change selectionMatch color so it better matches the vs code theme (grey instead of brown)
 - Uncomment updateOutput function (should be on)

Fixes: https://github.com/cue-lang/cue/issues/3239

To test:
Go to /play
Select a part of the code: it should be darkgrey now Double-click a word: it should be darkgrey instead of brown

2024-06-22 16:46 UTC, myitcv approved these changes
LGTM

2024-06-22 17:06 UTC, jpluscplusm requested changes
My initial impression is that whilst this improves the UX, there are now two different colours for selected text on the "current" line versus selected text on any /other/ line. I think the current-line colour should be aligned with the other-lines colour.

To see what I mean, open the preview at https://cl-1196613-1--cue-cls.netlify.app/play/#w=function&i=cue&f=eval&o=cue and swipe-and-select text from more than one line. Or just ctrl-A to select the whole pane - the last line will be highlighted in the current-line colour.

2024-06-22 18:35 UTC, myitcv commented
Nicely spotted, @jpluscplusm - this is indeed a problem. Appears to be a result of the current line highlight colour getting in the way (or mixing in some way with the selected text highlight). Perhaps we just turn off the current line highlight? It's a bit annoying, and with these sorts of weird interactions it's definitely not critical.

2024-06-24 07:18 UTC, JorindeUsMedia commented
I was also in doubt about just turning the highlight line off so I will do that. @myitcv @jpluscplusm

2024-06-24 10:37 UTC, myitcv commented
Now that my eye has been brought to the attention of issues in this space, one more tiny problem. Consider:

![Screenshot 2024-06-24 at 11 35 01](https://github.com/cue-lang/cuelang.org/assets/3374574/e1515207-c30a-4f33-ad9a-4a5dc1b74722)

There are two areas highlighting. Which one is selected, and which is highlighted as a result of the first?

Perhaps this isn't an issue in Visual Studio, but this seems confusing to me because if I were to hit delete it wouldn't be immediately obviously which would one or both would be deleted. 

@JorindeUsMedia - any experience from other editors here on what's normal?

2024-06-24 10:42 UTC, JorindeUsMedia commented
@myitcv We can make them a different color. From @jpluscplusm 's comment I understood you wanted them to be the same color.  But maybe I misunderstood because we had 2 problems: multi select vs select and line select (now turned off) vs manual select

2024-06-24 10:47 UTC, myitcv commented
Ok let's go with this for now and we can revisit after some local testing!

2024-06-24 10:48 UTC, myitcv commented
(I'll also have a look at what is causing the problems on your side with the PRs - the steps I outlined should have fixed the problem)

2024-06-24 10:54 UTC, jpluscplusm commented
I've re-imported the PR as of the most recent push and mailed it to https://cuelang.org/cl/1196613, replacing the previous CL so we can see a preview.

2024-06-24 11:48 UTC, jpluscplusm approved these changes
This looks good to me (preview at https://cl-1196613-2--cue-cls.netlify.app/play/#w=function&i=cue&f=eval&o=cue).

2024-06-24 11:51 UTC, closed without merging