hugo: Fix scroll on code tabs element
cue-lang/cuelang.org pull request #473
Opened 2024-10-22 11:15 UTC by Wies-UsMedia

This fixes an issue where the filenames in a code-tabs element can't be
scrolled horizontally if they are collectively wider than the element.
An example of this happening is on
https://cuelang.org/docs/concept/using-the-cue-export-command/inputs/#cue-package-file-inputs

Fixes cue-lang/cue#3502

--

To test, go to https://deploy-preview-473--cue.netlify.app/docs/concept/using-the-cue-export-command/inputs/#cue-package-file-inputs and see underneath the line "In all these situations the inputs are unified".

2024-10-22 11:43 UTC, JorindeUsMedia requested changes
The scrollbar is pretty big in desktop browsers. Maybe you can style the scrollbar?
I also noticed there is a vertical scrollbar showing: that is not needed. But maybe it's caused by the big scrollbar making the tab to high.
![image](https://github.com/user-attachments/assets/be8b8fd7-b526-4505-bd59-f207b005b60e)

2024-10-22 12:03 UTC, Wies-UsMedia commented
> The scrollbar is pretty big in desktop browsers. Maybe you can style the scrollbar? I also noticed there is a vertical scrollbar showing: that is not needed. But maybe it's caused by the big scrollbar making the tab to high. ![image](https://private-user-images.githubusercontent.com/122357989/378822982-be8b8fd7-b526-4505-bd59-f207b005b60e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTg3MTYsIm5iZiI6MTcyOTU5ODQxNiwicGF0aCI6Ii8xMjIzNTc5ODkvMzc4ODIyOTgyLWJlOGI4ZmQ3LWI1MjYtNDUwNS1iZDU5LWYyMDdiMDA1YjYwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQxMjAwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOWZkOGEyYWMwZTU3MGI3NWEwYjRkMDI0OWQzMGFlYzdmNjA1ZjhmNDBjZTkxOWNkZTRjZWZiMGI5MTMyY2IyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XByaSmxHI4oE--R1Zk_bWMEN3GG3kg1XNskERbfBQh0)

Didn't get a y-scroll in Firefox but did in Chrome after testing. Should be fixed now.

2024-10-22 12:09 UTC, JorindeUsMedia approved these changes

2024-10-24 13:34 UTC, jpluscplusm requested changes
This looks good on the preview. I'd prefer it if the scroll bar didn't disappear when not in use, in order to give the user a visual indication that there are filenames to scroll, but I'll capture that in a follow up.

I have some suggestions for the commit message. Here's the original:

```
- Modified scrollbar styling to code tabs

To test: go to
`docs/concept/using-the-cue-export-command/inputs/#cue-package-file-inputs`
and find the code-tabs element that overflows. It is beneath the line
'In all these situations the inputs are unified,'.

Fixes https://github.com/cue-lang/cue/issues/3502

Signed-off-by: Wies de Graaf <wies.de.graaf@usmedia.nl>
```

I would prefer to see this split into 2 sections: the persistently useful information in the commit message, and the info on how to test in the PR's opening comment. To show you what I mean, here's how I would construct those 2 elements:

## Commit message

- Subject: as per original
- Body:

```
This fixes an issue where the filenames in a code-tabs element can't be
scrolled horizontally if they are collectively wider than the element.
An example of this happening is on
https://cuelang.org/docs/concept/using-the-cue-export-command/inputs/#cue-package-file-inputs.

Fixes cue-lang/cue#3502

Signed-off-by: Wies de Graaf <wies.de.graaf@usmedia.nl>

```

## PR comment:

```
As per commit.

To test, go to $PREVIEW/docs/concept/using-the-cue-export-command/inputs/#cue-package-file-inputs and see underneath the line "In all these situations the inputs are unified".
```

Notice that the URL in the commit message is useful after the PR is merged, hence can link to cuelang.org; but the PR comment can reference the preview (I'd actually use the `$PREVIEW` pseudocode - I'm not suggesting you have to edit a clickable link in, afterwards!) and include more low-level testing information that's not valuable to capture as part of the persistent git-history of this change.

2024-10-25 06:42 UTC, Wies-UsMedia commented
Commit and PR message have been modified, and written down notes for next time!

2024-10-25 07:29 UTC, Wies-UsMedia commented
As for the scrollbar: if you use Firefox like me, that is a browser dependent option. The scrollbar is always visible on Chrome by default, and on Firefox you can enable it here:
![image](https://github.com/user-attachments/assets/6123bd77-0462-475e-bd93-3d5bafea1ffa)

2024-10-25 07:47 UTC, jpluscplusm approved these changes
LGTM! Importing now.

2024-10-25 08:44 UTC, closed without merging